name: Deploy to S3

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  workflow_dispatch:
  workflow_run:
    workflows: ["Sync Submodules"]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.action != 'closed' }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Zola
        uses: shalzz/zola-deploy-action@v0.19.2
        env:
          BUILD_ONLY: true

      - name: Upload official docs
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          aws s3 cp --recursive public s3://br-www-docs/blueos/${{ github.ref_name }}

      - name: Upload proposal preview
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          aws s3 cp --recursive public s3://br-www-docs/preview/blueos/pull/${{ github.event.pull_request.number }}

  cleanup:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.action == 'closed' }}
    steps:
      - name: Remove proposal preview
        run: |
          aws s3 rm --recursive s3://br-www-docs/preview/blueos/pull/${{ github.event.pull_request.number }}

